### ISSUE TITLE
On Trigger acquisition

### ISSUE THREAD

**Issue by werefkin** [alex123go/RedPitaya_Acquisition#4]
Hi! First of all - very nice down! 
That is what I was looking for! 
Just a short question, can on-trigger acquisition (to get signal synchronized with the reference signal) be implemented somehow easily?

Best,
Ivan

**Comment by alex123go** [comment]
Thanks a lot.

If you want to start the acquisition with an external trigger, that would be fairly easy.

However, if you want the moment the trigger happens to be in the acquisition window, we need to implement a circular buffer or some sort of pre-buffer. 

If you need the former, tell me and I'll modify it right away.
For the latter, I will need it in the next months for a project. I'll take the time to implement it by then.

**Comment by werefkin** [comment]
Hi! 
Thanks for the quick reply! 
Generally speaking, your idea to implement a high-speed digitizer based on the RP is great, I really liked it and understand how much efforts are/were needed here, I was surprised that these activities are not so intense.

To have it as a versatile tool, I think yes, an on-trigger acquisition (either external trigger or channel 2) option is quite important, I would rather think about your first suggestion I think in most of the applications it should be enough -- just to start acquisition when trigger arrived.

Another question that raised while playing with your solution (I use the nonGui version as I have to acquire/store/post-process some data) -- is it possible to change the sampling rate from the max of 125 Ms/s? I think that it would be great (e.g. in the default streaming app of the RP it is possible). 
My signals are rather slow (e.g. 20 ms duration to have like 2000 points will be enough) but they are a lot faster than SCPI communication (that is why I am looking for such a solution) which I am currently using and which makes my overall measurement time too slow. 

Best,
Ivan

**Comment by werefkin** [comment]
Just got an idea, 
with your solution, it is possible to sample at the full speed of 125 MS/s covering e.g. 1.6 sec which is a lot,

Maybe some decimation can be realised directly on the RP to not transfer the whole amount of data? 
Best,
Ivan

**Comment by alex123go** [comment]
Hi,

Yes I agree, an external trigger should be added. I'll try to do it when I'll have a Red Pitaya with me.
I also want to add a trigger to the signal (just like an oscilloscope), but it'll takes a bit more time.

About the decimation, it's not currently implemented. The easy solution would be to acquire 1 point every n clock cycle, however, it's not optimal. The ideal approach is to "average" n points and output 1. However this approach is already done by the default streaming app, so I don't see the use case to do it here.
Also, if the transfer time is not that important and 1.6 seconds is long enough, you could decimate in python before saving (look at scipy.signal.decimate).

You can also take a look at Nils' app (https://forum.redpitaya.com/viewtopic.php?f=7&t=317) as well at Pavel's app ( https://github.com/pavel-demin/red-pitaya-notes). If I remember correctly, Pavel uses a nice decimation scheme.

Regards,
Alex

**Comment by werefkin** [comment]
Hi Alex,

Ok, you understood me wrong with 1.6 sec -- it is too long of course. I just thought about a solution that, for example, we record a lot of samples over e.g. 0.05 sec (it is something like my measurement time) at the maximum speed (so 125 Ms/s * 0.05 s) and then do decimation on the red pitaya directly to transfer already downsampled signals (i.e. so it is faster).

I think both your ideas are more elegant, simply to acquire 1 point each e.g. 100 times or using averaging. 
In this context, the default streaming app is also not a good solution, it cannot be triggered, that is a point.

Yes, of course, I did try the decimation afterwards already in python -- but it was so that I have to acquire a very big dataset (so a lot of time to transfer it) then manipulate it to downsample with decimation (again a lot of time) -- that was a big issue and worked a lot slower than even SCPI.

Do you think there is a possibility to implement such decimation? I think even the first option (1 point every n clock would already be nice).

Thanks, I will take a look on the apps

Best,
Ivan

**Comment by alex123go** [comment]
Yes, it's not that difficult to implement. I'll take a look at that soon.

In the mean time, I suggest you try to implement "adc_recorder_trigger" from Pavel ( https://github.com/pavel-demin/red-pitaya-notes ). 

You can read his notes here : https://pavel-demin.github.io/red-pitaya-notes/

Make sure to read this page to know how to build the project in vivado : https://pavel-demin.github.io/red-pitaya-notes/

It offers decimation before recording, a trigger sync with an external source and recording up to 32MSamples (if I recall correctly) at the sampling rate you decided with the decimation.

**Comment by werefkin** [comment]
Hi Alex,

thank you a lot for the links and communication
Hmm, well, yes adc_recorder_trigger seems to be the right implementation. 
I have read about vivado and building the project, it seems (to me) feasible, but what I see as challenging is that communication with python is not considered here. As I can see, there is a C code and a Tcl code for vivado only. As I am new to this system in general I find it quite undefined how to do it. 
I seems that the communication is realized in another project adc_test (although implemented in C where I am not so experienced), but it has different functionality. 

I will try to look into it and play but really looking forward to your pythonic implementation. I built some data processing algorithms in python, which is crucial for me, and the problem was scpi speed which -- i realized using your project -- is not a limit.

Best,
Ivan

**Comment by alex123go** [comment]
I've add the downsampling (without averating, only keep 1 point every n clock cycles) and the external trigger.

**Comment by werefkin** [comment]
> I've add the downsampling (without averating, only keep 1 point every n clock cycles) and the external trigger.

Hi Alex,
Thanks, I am happy to check it when I am back to this part of the project
